# Generated by Django 5.1.2 on 2024-10-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
